added LSB-Tools

diff --git a/LFSPkgBuildScripts/kernel/wireless_script b/LFSPkgBuildScripts/kernel/wireless_script
--- a/LFSPkgBuildScripts/kernel/wireless_script
+++ b/LFSPkgBuildScripts/kernel/wireless_script
@@ -83,19 +83,19 @@ if [ -f /etc/NetworkManager/nm-system-settings.conf ]; then
     grep -v '^#' /etc/NetworkManager/nm-system-settings.conf
 fi
 
-printf "\n##### iwlist #####\n\n"
-if [ -t 0 ]; then
-    sudo iwlist scan || echo "Aquiring of root rights failed."
-elif [ -x /usr/bin/gksudo ]; then
-    gksudo iwlist scan || echo "Aquiring of root rights failed."
-elif [ -x /usr/bin/kdesudo ]; then
-    kdesudo iwlist scan || echo "Aquiring of root rights failed."
-else
-    echo "No way to aquire root rights found."
-fi
-
-printf "\n##### iwlist channel #####\n\n"
-iwlist chan
+#printf "\n##### iwlist #####\n\n"
+#if [ -t 0 ]; then
+#    sudo iwlist scan || echo "Aquiring of root rights failed."
+#elif [ -x /usr/bin/gksudo ]; then
+#    gksudo iwlist scan || echo "Aquiring of root rights failed."
+#elif [ -x /usr/bin/kdesudo ]; then
+#    kdesudo iwlist scan || echo "Aquiring of root rights failed."
+#else
+#    echo "No way to aquire root rights found."
+#fi
+#
+#printf "\n##### iwlist channel #####\n\n"
+#iwlist chan
 
 printf "\n##### lsmod #####\n\n"
 lsmod | egrep "(^|[[:punct:] ])${MODMATCHES}([[:punct:] ]|$)"
@@ -132,7 +132,7 @@ exec 1>&3 3>&-
 exec 2>&4 4>&-
 
 RESULTS=$(cat -s $FILEBASE.txt)
-sed 's/\([[:alnum:]][[:alnum:]]:\)\{5\}[[:alnum:]][[:alnum:]]/<MAC address removed>/' <<< "$RESULTS" > $FILEBASE.txt
+#sed 's/\([[:alnum:]][[:alnum:]]:\)\{5\}[[:alnum:]][[:alnum:]]/<MAC address removed>/' <<< "$RESULTS" > $FILEBASE.txt
 
 if [ $(stat -c %s $FILEBASE.txt) -gt 19968 ]; then
     tar -czf $FILEBASE.tar.gz $FILEBASE.txt
