updated update script and main system packages

diff --git a/Updating/UpdateBuildScripts b/Updating/UpdateBuildScripts
--- a/Updating/UpdateBuildScripts
+++ b/Updating/UpdateBuildScripts
@@ -9,7 +9,7 @@ else
 	exit 1
 fi
 
-#(cd ../LFSScripts;./ShowSystemData)||true
+(cd ../LFSScripts;./ShowSystemData)||true
 
 RED='\e[1;31m'
 GREEN='\e[1;32m'
@@ -24,10 +24,13 @@ INSTALLEDVERSION=""
 UPDATETOVERSION=""
 PATHTOSCRIPT=""
 INLINE=${INLINE:-"-i"}
+FORCEVERSION="$2"
+CURRENTVERSION=""
+UPDATESCRIPT=1
 
 parseArray ()
 {
-for ((j=0;j<${#RESULTS};j++))
+for ((j=0;j<${#RESULTS[@]};j++))
 	do
 		if [ "X${RESULTS[j]}" != "X" ];then
 			case ${RESULTS[j]} in
@@ -42,6 +45,13 @@ for ((j=0;j<${#RESULTS};j++))
 				"Path to script="*)
 					PATHTOSCRIPT=${RESULTS[j]##*=}
 					PATHTOSCRIPT=${LFS}${PATHTOSCRIPT//[$'\t\r\n ']}
+					;;
+				*"is Ok"*)
+				echo "is ok"
+					CURRENTVERSION="$PACKAGETOTEST-$(echo ${RESULTS[j]}|awk '{print $4}')"
+					UPDATETOVERSION=$(echo ${RESULTS[j]}|awk '{print $4}')
+					UPDATESCRIPT=0
+					;;
 			esac
 		fi
 	done	
@@ -52,40 +62,51 @@ if [ "X$PACKAGETOTEST" = "X" ];then
 	exit 1
 fi
 
-if [ "X$(lfspkg -R $LFS -C $PACKAGETOTEST 2>&1|grep -i 'No version info for')" != "X" ];then
-	echo "Can't find version info for $PACKAGETOTEST ..."
-	exit 1
+if [ "X$FORCEVERSION}" = "X" ];then
+	if [ "X$(lfspkg -R $LFS -C $PACKAGETOTEST 2>&1|grep -i 'No version info for')" != "X" ];then
+		echo "Can't find version info for $PACKAGETOTEST ..."
+		exit 1
+	fi
+else
+	UPDATETOVERSION=$FORCEVERSION
 fi
 
-readarray RESULTS < <(lfspkg -R $LFS -C $PACKAGETOTEST 2>/dev/null)
-parseArray
+if [ "X${FORCEVERSION}" = "X" ];then
+	readarray RESULTS < <(lfspkg -R $LFS -C $PACKAGETOTEST 2>&1)
+else
+	readarray RESULTS < <(lfspkg -R $LFS -S $PACKAGETOTEST 2>&1)
+fi
 
-if [ "X$INSTALLEDVERSION" = "X" ] || [ "X$UPDATETOVERSION" = "X" ] || [ "X$PATHTOSCRIPT" = "X" ];then
+parseArray
+#echo -e ">>$INSTALLEDVERSION $UPDATETOVERSION $PATHTOSCRIPT $CURRENTVERSION<<"
+#exit
+if [ "X$INSTALLEDVERSION" = "X" ] || [ "X$UPDATETOVERSION" = "X" ] || [ "X$PATHTOSCRIPT" = "X" ] && [ "X$CURRENTVERSION" = "X" ];then
 	echo -e "${RED}Can't auto-update $PACKAGETOTEST ...${NORMAL}"
 	lfspkg -R $LFS -S $PACKAGETOTEST
 	echo "....."
-	lfspkg -R $LFS -C $PACKAGETOTEST 2>/dev/null
+	lfspkg -R $LFS -C $PACKAGETOTEST
 	exit 1
 fi
 
 echo -e "${GREEN}Auto-update $PACKAGETOTEST $INSTALLEDVERSION to $UPDATETOVERSION${NORMAL}\n"
 
-readarray DEPENDSON < <(lfspkg -R $LFS -O $PACKAGETOTEST 2>/dev/null)
-for ((j=1;j<${#DEPENDSON};j++))
+readarray DEPENDSON < <(lfspkg -R $LFS -O $PACKAGETOTEST 2>&1)
+for ((j=1;j<${#DEPENDSON[@]};j++))
 	do
 		if [ "X${DEPENDSON[j]}" != "X" ];then
 			DEPENDFILE=${DEPENDSON[j]##*- }
 			DEPENDFILE=${DEPENDFILE//[$'\t\r\n ']}
 			echo -e "${GREEN}Updating $DEPENDFILE ...${NORMAL}"
-#			sed $INLINE "s|\(\b${PACKAGETOTEST}\b\)-[0-9].*|\1-$UPDATETOVERSION|gI" $DEPENDFILE
-			sed $INLINE "s|\(\b${PACKAGETOTEST}\b\)-[0-9][.0-9]*|\1-$UPDATETOVERSION|gI" $DEPENDFILE
+			sed $INLINE "s|\([^-]\b${PACKAGETOTEST}\b\)-[0-9][.0-9]*|\1-$UPDATETOVERSION|gI;s|^\(\b${PACKAGETOTEST}\b\)-[0-9][.0-9]*|\1-$UPDATETOVERSION|gI"  $DEPENDFILE
 		fi
 	done
 
 echo
 
 echo -e "${GREEN}Please check $PATHTOSCRIPT ...${NORMAL}"
-sed $INLINE "s|VERSION=.*|VERSION=\"$UPDATETOVERSION\"|" "$PATHTOSCRIPT"
+if [ $UPDATESCRIPT -eq 1 ];then
+	sed $INLINE "s|VERSION=.*|VERSION=\"$UPDATETOVERSION\"|" "$PATHTOSCRIPT"
+fi
 xdg-open "$PATHTOSCRIPT" &>/dev/null
 
 
