udated pi-kodi to leia

diff --git a/LFSPkgBuildScripts/mm/kodi/kodi b/LFSPkgBuildScripts/mm/kodi/kodi
--- a/LFSPkgBuildScripts/mm/kodi/kodi
+++ b/LFSPkgBuildScripts/mm/kodi/kodi
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-#      Copyright (C) 2008-2013 Team XBMC
-#      http://xbmc.org
+#      Copyright (C) 2008-2017 Team XBMC
+#      http://kodi.tv
 #
 #  This Program is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
@@ -25,8 +25,10 @@ prefix="/usr"
 exec_prefix="/usr"
 datarootdir="/usr/share"
 LIBDIR="/usr/lib"
+APP_BINARY=$LIBDIR/${bin_name}/kodi-rbpi
 CRASHLOG_DIR=${CRASHLOG_DIR:-$HOME}
-USERDATA_DIR="${HOME}/.${bin_name}"
+KODI_DATA=${KODI_DATA:-"${HOME}/.${bin_name}"} # mapped to special://home/
+WINDOWING=${WINDOWING:-"auto"}
 
 # Black Screen on exit fix
 ORIGINAL_DEPTH=`fbset | head -3 | tail -1 | cut -d " " -f 10`
@@ -68,7 +70,6 @@ export __GL_YIELD=USLEEP
 # Fix wasting RAM due to fragmentation
 export MALLOC_MMAP_THRESHOLD_=131072
 
-
 # Check for some options used by this script
 while [ "$#" -gt "0" ]
 do
@@ -77,21 +78,56 @@ do
             LIBDIR="$2"
             shift; shift
             ;;
+        --windowing)
+            WINDOWING="$2"
+            echo "$SAVED_ARGS" | sed "s/--windowing[ ]*$2//g"
+            shift; shift
+            ;;
         *)
             shift
             ;;
     esac
 done
 
+# Note: by default only one of those binaries exists
+# To be able to select a different one, if has to be compiled specifically
+# Your distribution might provide extra packages for those
+if [ "$WINDOWING" = "auto" ]; then
+    # Wayland
+    if [ -n "$WAYLAND_DISPLAY" ] && [ -x $LIBDIR/${bin_name}/${bin_name}-wayland ]; then
+        KODI_BINARY=$LIBDIR/${bin_name}/${bin_name}-wayland
+    # X11
+    elif echo $DISPLAY | grep -qE ":[0-9]+" && [ -x $LIBDIR/${bin_name}/${bin_name}-x11 ]; then
+        KODI_BINARY=$LIBDIR/${bin_name}/${bin_name}-x11
+    # GBM/DRM
+    elif [ -z "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && [ -x $LIBDIR/${bin_name}/${bin_name}-gbm ]; then
+        KODI_BINARY=$LIBDIR/${bin_name}/${bin_name}-gbm
+    # Default kodi.bin
+    else
+        KODI_BINARY=${APP_BINARY}
+    fi
+elif [ -n "$WINDOWING" ]; then
+    KODI_BINARY=$LIBDIR/${bin_name}/${bin_name}-${WINDOWING}
+else
+    KODI_BINARY=${APP_BINARY}
+fi
+
+if [ ! -x ${KODI_BINARY} ]; then
+    echo "Error: ${KODI_BINARY} not found"
+    exit 2
+fi
+
+APPORT_CORE="/var/crash/$(echo -n ${KODI_BINARY}|tr / _).$(id -u).crash"
+
 migrate_home()
 {
   [ "$(basename $0)" = "xbmc" ] && echo "WARNING: Running ${bin_name} as "xbmc" is deprecated and will be removed in later versions, please switch to using the ${bin_name} binary"
 
   #check if data migration is needed
-  if [ -d "${HOME}/.xbmc" ] && [ ! -d "${USERDATA_DIR}" ]; then
-      echo "INFO: migrating userdata folder. Renaming ${HOME}/.xbmc to $USERDATA_DIR"
-      mv ${HOME}/.xbmc $USERDATA_DIR
-      touch ${USERDATA_DIR}/.kodi_data_was_migrated
+  if [ -d "${HOME}/.xbmc" ] && [ ! -d "${KODI_DATA}" ]; then
+      echo "INFO: migrating userdata folder. Renaming ${HOME}/.xbmc to $KODI_DATA"
+      mv ${HOME}/.xbmc $KODI_DATA
+      touch ${KODI_DATA}/.kodi_data_was_migrated
   fi
 }
 
@@ -104,10 +140,10 @@ single_stacktrace()
 {
   # core filename is either "core.$PID" or "core"
   find "$1" -maxdepth $2 -name 'core*' | while read core; do
-      LC_ALL=C gdb --core="$core" --batch 2> /dev/null | grep -q "^Core was generated by \`$LIBDIR/${bin_name}/${bin_name}.bin" || continue
+      LC_ALL=C gdb --core="$core" --batch 2> /dev/null | grep -q "^Core was generated by \`${KODI_BINARY}" || continue
       echo "=====>  Core file: "$core" ($(stat -c%y "$core"))" >> $FILE
       echo "        =========================================" >> $FILE
-      gdb "$LIBDIR/${bin_name}/${bin_name}.bin" --core="$core" --batch -ex "thread apply all bt" 2> /dev/null >> $FILE
+      gdb "${KODI_BINARY}" --core="$core" --batch -ex "thread apply all bt" 2> /dev/null >> $FILE
       rm -f "$core"
   done
 }
@@ -140,9 +176,17 @@ print_crash_report()
   echo "############### STACK TRACE #################" >> $FILE
   if command_exists gdb; then
     if command_exists systemd-coredumpctl; then
-      systemd-coredumpctl dump -o core ${bin_name}.bin > /dev/null 2>&1
+      systemd-coredumpctl dump -o core $(basename ${KODI_BINARY}) > /dev/null 2>&1
     elif command_exists coredumpctl; then
-      coredumpctl dump -o core ${bin_name}.bin > /dev/null 2>&1
+      coredumpctl dump -o core $(basename ${KODI_BINARY})  > /dev/null 2>&1
+    elif command_exists apport-unpack && test -f "${APPORT_CORE}"; then
+      TMP_DIR="$(mktemp -d -p ${HOME})"
+      if [ -d "${TMP_DIR}" ]; then
+        rm -f "${HOME}/core"
+        apport-unpack "${APPORT_CORE}" "${TMP_DIR}"
+        mv "${TMP_DIR}/CoreDump" "${HOME}/core"
+        rm -rf "${TMP_DIR}"
+      fi
     fi
     single_stacktrace "$PWD" 1
     # Find in plugins directories
@@ -166,9 +210,9 @@ print_crash_report()
   echo >> $FILE
   echo "################# LOG FILE ##################" >> $FILE
   echo >> $FILE
-  if [ -f $USERDATA_DIR/temp/kodi.log ]
+  if [ -f $KODI_DATA/temp/kodi.log ]
   then
-    cat $USERDATA_DIR/temp/kodi.log >> $FILE
+    cat $KODI_DATA/temp/kodi.log >> $FILE
     echo >> $FILE
   else
     echo "Logfile not found in the usual place." >> $FILE
@@ -195,8 +239,9 @@ fi
 LOOP=1
 while [ $(( $LOOP )) = "1" ]
 do
+  [ -f "${APPORT_CORE}" ] && rm -f "${APPORT_CORE}"
   LOOP=0
-  "$LIBDIR/${bin_name}/${bin_name}.bin" $SAVED_ARGS
+  ${KODI_BINARY} $SAVED_ARGS
   RET=$?
   if [ $(( $RET == 65 )) = "1" ]
   then # User requested to restart app
@@ -205,7 +250,7 @@ do
   then # Crashed with core dump
     print_crash_report
   fi
-done 2>&1 >/dev/null
+done
 
 # Raspberry Pi fixes
 restore_screen_mode
